name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://service-catalogue.zozo-inc.com/
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: ./build.sh

      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

      - name: deploy
        uses: actions/deploy-pages@v1
